# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    image: postgresql
    # environment:
    #   - POSTGRES_USER=${PG_USER:orc}
    #   - POSTGRES_PASSWORD=${PG_PASSWORD:orc}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=orc.conf.docker
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:


  # See: src/orc/conf/docker.py
  # Optional containers below:
#  elasticsearch:
#    # NOTE: No persistance storage configured.
#    # See: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - cluster.routing.allocation.disk.threshold_enabled=false
#    ports:
#      - 9200:9200
#  redis:
#    # NOTE: No persistance storage configured.
#    # See: https://hub.docker.com/_/redis/
#    image: redis
#    ports:
#        - 6379:6379
